### ISSUE TITLE
Add setting for dark mode for reduced eye strain

### ISSUE THREAD

**Issue by anidealchaos** [calvinf/versesforlife-app#26]
Easy on the eyes and in dimly lit situations where a bright screen might distract others (ex. public transit)

![img_8398](https://cloud.githubusercontent.com/assets/13595368/20862584/b99e9058-b963-11e6-93df-1812ed9bf715.PNG)

**Comment by calvinf** [comment]
Good suggestion.  It's on the backlog. 👍
